// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    VvButton: typeof import('@volverjs/ui-vue/vv-button')['default']
    VvCard: typeof import('@volverjs/ui-vue/vv-card')['default']
    VvInputText: typeof import('@volverjs/ui-vue/vv-input-text')['default']
  }
}
